### ISSUE TITLE
Migration difficulties to sentry-logback 4.0.0 (from 1.7.30)

### ISSUE THREAD

**Issue by dreis2211** [getsentry/sentry-java#1215]
_Platform:_
- [x]  Java -> 11
- [x]  Logback -> 1.2.3
- [x]  Spring -> Spring Boot 2.3.9

The version of the SDK:
**4.0.0**

---
Hi,

I wanted to migrate to the new 4.0.0 SDK as 1.7.x doesn't seem to be under active development anymore. Unfortunately, I hit some really big roadblocks that makes it somewhat impossible to migrate away from 1.7.x.

E.g. in 1.7 we extended our own Appender from `SentryAppender` that could be referenced in the logback.xml and that was customized roughly like this. Which now horribly breaks with compiler errors.

```
	@Override
	protected EventBuilder createEventBuilder(ILoggingEvent loggingEvent) {
		EventBuilder eventBuilder = super.createEventBuilder(loggingEvent);
		HttpServletRequest request = getHttpServletRequest();

		// add release to sentry logs
		eventBuilder.withRelease(getReleaseVersion());

		if (request != null) {
			// add user data if present
			getUserInterface(request).ifPresent(eventBuilder::withSentryInterface);

			// filter some header information from the current request
			eventBuilder.withSentryInterface(new HeaderFilteringHttpInterface(request, remoteAddressResolver), false);
		}

		return eventBuilder;
	}

```

Unfortunately, neither the migration guides nor the changelogs really mention something about this - at least I couldn't find anything that helped me. Looking into the new API of `SentryAppender` it seems to be impossible to customize our appender like this anymore. `createEvent` (and even `SentryAppender` itself) seems to be final and every interface (`UserInterface`, `HttpInterface` etc.) that was there before seems to be gone without replacement.

If I simply didn't find the information, I'm very sorry, but could you please shed some light on how one could migrate this sort of setup to the new version?

Thank you.
Cheers,
Christoph

**Comment by maciejwalkowiak** [comment]
@dreis2211 could you please explain a bit more what does your custom appender do differently? Perhaps there is another way to do it now.

When `sentry-logback` is used together with `sentry-spring-boot`, request information is added automatically to events sent from `SentryAppender`.

**Comment by dreis2211** [comment]
@maciejwalkowiak As noted in the code-snippet it sets the release version (that is sort of dynamic, so we can't configure it upfront).

It also does some header filtering to be GDPR compliant by setting a sentry interface, which does not exist anymore :
```
public class HeaderFilteringHttpInterface extends HttpInterface {

	private static final List<String> FILTERED_HEADERS = Arrays.asList(
		"X-Forwarded-For".toLowerCase(),
		"X-Real-Ip".toLowerCase()
	);

	public HeaderFilteringHttpInterface(HttpServletRequest request, RemoteAddressResolver remoteAddressResolver) {
		super(request, remoteAddressResolver);
	}

	@Override
	public Map<String, Collection<String>> getHeaders() {
		return super.getHeaders().entrySet().stream()
			.filter(entry -> !FILTERED_HEADERS.contains(entry.getKey().toLowerCase()))
			.collect(Collectors.toMap(Map.Entry::getKey, Map.Entry::getValue));
	}
}
```

Secondly, it's checking for a user-id in our headers - also via interfaces that do not exist anymore:
```
	private Optional<UserInterface> getUserInterface(HttpServletRequest request) {
		return HttpServletUtils.getUserIdFromRequest(request)
			.map(String::valueOf)
			.or(() -> this.getUserIdFromHeaders(request))
			.map(userId -> new UserInterface(userId, "", "", ""));
	}
```

And then there is some extra tags based on the MDC property map.
```
	private void addTagFromMDC(EventBuilder eventBuilder, ILoggingEvent loggingEvent, String key) {
		Map<String, String> map = loggingEvent.getMDCPropertyMap();
		if (map.containsKey(key)) {
			eventBuilder.withTag(key, map.get(key));
		}
	}
```

I'm working in a service department, so while we provide a general implementation our internal customers could derive from our appender as well and customize the `eventBuilder` even further.

I should mention we're not using `sentry-spring-boot`, we just use `sentry-logback` and have a minimal `Sentry.init()` call in a `@Configuration` class.

**Comment by dreis2211** [comment]
I'm sort of seeing some way out if we use `EventProcessor`s but that I still see no equivalent to filter the headers or the user information (so essentially everything that was based on the `SentryInterface` beforehand)

**Comment by maciejwalkowiak** [comment]
Yes, with `EventProcessor` you can modify the event before its sent to Sentry. Please give it a try and if you wont succeed we will figure out how we can relax or make `SentryAppender` more configurable.

**Comment by marandaneto** [comment]
@dreis2211 did you manage to get it working with `EventProcessors`?

you can mutate an event either using `event processors` https://develop.sentry.dev/sdk/unified-api/#terminology or the `before send` callback https://docs.sentry.io/platforms/java/configuration/options/#before-send

**Comment by marandaneto** [comment]
Closing the issue as a part of large repository cleanup, due to it being inactive and/or outdated. There's a large chance that this issue has been solved since.
Please do not hesitate to ping me if it is still relevant, and I will happily reopen and work on it.
Cheers!

**Comment by dreis2211** [comment]
Wasn't solved until today, but I see a good chance of using the EventProcessor. This could be mentioned in the migration docs. I think more people will have a custom `SentryAppender` that they won't be able to use anymore.

**Comment by marandaneto** [comment]
I agree that the migration page could be richer, although we have this note:

> Our update to the API follows the Unified API more closely. It's a completely updated code base, written to support our Android SDK.

and it links to the Unified API page which is the one shared above, it does explain pretty much how to do the things using the new API, let us know if you find issues using the EventProcessor and we'd gladly figure this out, thanks.
