### ISSUE TITLE
Sentry Logback with Spring Boot does not pickup configuration from Spring

### ISSUE THREAD

**Issue by rharrahuzurv** [getsentry/sentry-java#4521]
### Integration

sentry

### Java Version

24

### Version

8.15.0

### Steps to Reproduce

Use a Spring Boot 3.4.5 application with Sentry 8.15.0 and enable Sentry logging:
```yaml
sentry:
  dsn: mydsngoeshere
  send-default-pii: true
  environment: ${ENVIRONMENT_NAME}
  logs:
    enabled: true
  logging:
    minimum-level: info
    minimum-event-level: info
    minimum-breadcrumb-level: debug
    enabled: true
```

### Expected Result

Logs should appear in Sentry Logs.

### Actual Result

Logs do not appear in Sentry logs.

As of this line (https://github.com/getsentry/sentry-java/blob/main/sentry-spring-boot-jakarta/src/main/java/io/sentry/spring/boot/jakarta/SentryLogbackInitializer.java#L58), `SentryOptions$Logs` is correctly detecting from the Spring properties that logs are enabled:
<img width="285" alt="Image" src="https://github.com/user-attachments/assets/18e08dc9-6801-4fce-a7fb-bce8874f71d4" />

As of this line (https://github.com/getsentry/sentry-java/blob/8.15.0/sentry-logback/src/main/java/io/sentry/logback/SentryAppender.java#L71), `SentryOptions$Logs` is not using the properties, which is to be expected because these are external configurations:
<img width="288" alt="Image" src="https://github.com/user-attachments/assets/1cd0f775-b44c-4f7c-afd5-4695ac4ebd22" />

Once it reaches and invokes the method on this line (https://github.com/getsentry/sentry-java/blob/8.15.0/sentry/src/main/java/io/sentry/Sentry.java#L291) in `Sentry.init`, it should pick up the external configuration from Spring but does not. It resolves values from environment variables / system properties / classpath but never receives either the DSN or that logs are enabled configured in the Spring properties, resulting in logs never being sent:
<img width="1099" alt="Image" src="https://github.com/user-attachments/assets/f01807c1-c80e-4be6-ab15-ea901e864e2d" />
<img width="982" alt="Image" src="https://github.com/user-attachments/assets/877b5279-80c6-4740-abbd-e3fa49ea17df" />

**Comment by adinauer** [comment]
Thanks for opening this issue @rharrahuzurv we'll investigate. The SDK should re-initialize once Spring Boot has been loaded and then apply your `application.yml`.

So startup logs are not captured but anything after the Spring Boot `Sentry.init` should.
I presume you don't see any logs even after your applications has fully started, correct?

**Comment by adinauer** [comment]
Ah I think I found the issue. Will probably PR a fix soon.

**Comment by adinauer** [comment]
@rharrahuzurv https://github.com/getsentry/sentry-java/releases/tag/8.15.1 has just been released and should fix the problem.

**Comment by rharrahuzurv** [comment]
@adinauer I'm still seeing the issue but am getting a new logged warning, at least. Using 8.15.1:
<img width="368" alt="Image" src="https://github.com/user-attachments/assets/8f1dc09d-3e73-4afb-b6c3-ac9f6e134a5b" />

from console after enabling logback debugging:
> 13:23:16,511 |-WARN in io.sentry.logback.SentryAppender[SENTRY_APPENDER] - Failed to init Sentry during appender initialization: DSN is required. Use empty string or set enabled to false in SentryOptions to disable SDK.

**Comment by rharrahuzurv** [comment]
The above is a false positive, it's working now. Sorry for the confusion!

**Comment by adinauer** [comment]
Thanks for testing @rharrahuzurv.

That warning basically just means, you're not setting the DSN explicitly on the Logback Appender and thus won't have startup logs captured and sent to Sentry.

Do you see any other logs that could help us if you enable `sentry.debug: true` in your `application.yml`?

When starting our Spring Boot 3 demo application, I see the following in logs with `debug` enabled:
```
DEBUG: Serializing object: {"items":[{"timestamp":1750959420.002330,"trace_id":"a297c8df36ae4d9892bab1418b6896d8","body":"Started SentryDemoApplication in 10.514 seconds (process running for 10.691)","level":"info","severity_number":9,"attributes":{"sentry.message.template":{"type":"string","value":"Started SentryDemoApplication in 10.514 seconds (process running for 10.691)"},"server.address":{"type":"string","value":"localhost"},"sentry.sdk.name":{"type":"string","value":"sentry.java.spring-boot.jakarta"},"sentry.environment":{"type":"string","value":"production"},"sentry.sdk.version":{"type":"string","value":"8.15.1"},"sentry.trace.parent_span_id":{"type":"string","value":"c85eb481de6a4b07"}}}]}
```

Can you please check if you also see this?

**Comment by adinauer** [comment]
@rharrahuzurv ah that's great. Thank you for reporting and testing :-)
