### ISSUE TITLE
sentry-agent 8.18.0 causes hanging threads

### ISSUE THREAD

**Issue by omarhachach** [getsentry/sentry-java#4622]
### Integration

sentry-opentelemetry-agent

### Java Version

21

### Version

8.18.0

### Steps to Reproduce

This is in a Kotlin Jetty (12) Micronaut setup. I cannot share too many details, but I'll do my best with logs and and whatever insight I can get.

When upgrading from 8.17.0 to 8.18.0 we recorded an incident where our otel-agent started causing some requests to block eventually leading to hanging threads and db pool saturation.

Our configuration sample rate is 0.001. We have no custom Sentry or Otel instrumentation and solely rely on the agent.

I've been able to reproduce this consistently internally. We see a lot of this:
```
DEBUG: Creating Sentry transaction for OpenTelemetry span 0d72f01959891515 (trace 2865fb7d0865adc0a23d43be9ee591e8).
INFO: Tracing is disabled and this 'startTransaction' returns a no-op.
DEBUG: Creating Sentry child span for OpenTelemetry span b94634615255982c (trace 2865fb7d0865adc0a23d43be9ee591e8). Parent span is 0d72f01959891515.
DEBUG: Creating Sentry child span for OpenTelemetry span d26bfc6694427b8b (trace 2865fb7d0865adc0a23d43be9ee591e8). Parent span is b94634615255982c.
DEBUG: Creating Sentry child span for OpenTelemetry span f27175d881e68c3c (trace 2865fb7d0865adc0a23d43be9ee591e8). Parent span is 0d72f01959891515.
DEBUG: Creating Sentry child span for OpenTelemetry span 1b751e4180a28b6c (trace 2865fb7d0865adc0a23d43be9ee591e8). Parent span is 0d72f01959891515.
DEBUG: Creating Sentry child span for OpenTelemetry span d01afc21ad0be8b9 (trace 2865fb7d0865adc0a23d43be9ee591e8). Parent span is 0d72f01959891515.
DEBUG: Creating Sentry child span for OpenTelemetry span 1cb4fc2c5ebc91de (trace 2865fb7d0865adc0a23d43be9ee591e8). Parent span is d01afc21ad0be8b9.
DEBUG: Creating Sentry child span for OpenTelemetry span dec594822b956e45 (trace 2865fb7d0865adc0a23d43be9ee591e8). Parent span is 0d72f01959891515.
DEBUG: Creating Sentry child span for OpenTelemetry span 83e999a6b41f7a42 (trace 2865fb7d0865adc0a23d43be9ee591e8). Parent span is 0d72f01959891515.
DEBUG: Creating Sentry child span for OpenTelemetry span 9d2f257d5a78d7ff (trace 2865fb7d0865adc0a23d43be9ee591e8). Parent span is 0d72f01959891515.
DEBUG: Creating Sentry child span for OpenTelemetry span 57e65ef4e3caa751 (trace 2865fb7d0865adc0a23d43be9ee591e8). Parent span is 0d72f01959891515.
DEBUG: Creating Sentry child span for OpenTelemetry span 65e0f53158aca698 (trace 2865fb7d0865adc0a23d43be9ee591e8). Parent span is 57e65ef4e3caa751.
DEBUG: Creating Sentry child span for OpenTelemetry span 6880297cb4b6c2f5 (trace 2865fb7d0865adc0a23d43be9ee591e8). Parent span is 0d72f01959891515.
DEBUG: SpanExporter exported 13 spans, 0 unset spans remaining.
```
Before the crash. We do not see any 500s, only timeouts.

### Expected Result

The interesting thing, is that running the same load on 8.17.0 doesn't end in a crash, but produces errors instead:
```
java.lang.IllegalStateException: Request/Response does not exist (likely recycled)
	at org.eclipse.jetty.ee10.servlet.ServletChannel.getServletContextResponse(ServletChannel.java:283)
	at org.eclipse.jetty.ee10.servlet.ServletChannelState.isResponseCommitted(ServletChannelState.java:360)
	at org.eclipse.jetty.ee10.servlet.ServletChannel.isCommitted(ServletChannel.java:767)
	at org.eclipse.jetty.ee10.servlet.ServletApiResponse.isCommitted(ServletApiResponse.java:430)
	at io.micronaut.servlet.engine.DefaultServletHttpResponse$DelegateResponseMetadata.isCommitted(DefaultServletHttpResponse.java:662)
	at io.micronaut.servlet.engine.DefaultServletHttpResponse.isCommitted(DefaultServletHttpResponse.java:135)
	at io.micronaut.servlet.http.ServletHttpHandler.process(ServletHttpHandler.java:296)
	at io.micronaut.servlet.http.ServletHttpHandler.lambda$service$6(ServletHttpHandler.java:263)
	at io.micronaut.http.reactive.execution.ReactorExecutionFlowImpl.lambda$flatMap$0(ReactorExecutionFlowImpl.java:168)
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:132)
	at io.opentelemetry.javaagent.shaded.instrumentation.reactor.v3_1.TracingSubscriber.onNext(TracingSubscriber.java:68)
	at reactor.core.publisher.FluxHide$SuppressFuseableSubscriber.onNext(FluxHide.java:137)
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:158)
	at io.opentelemetry.javaagent.shaded.instrumentation.reactor.v3_1.TracingSubscriber.onNext(TracingSubscriber.java:68)
	at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onNext(FluxOnErrorResume.java:79)
	at io.opentelemetry.javaagent.shaded.instrumentation.reactor.v3_1.TracingSubscriber.onNext(TracingSubscriber.java:68)
	at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:122)
	at io.opentelemetry.javaagent.shaded.instrumentation.reactor.v3_1.TracingSubscriber.onNext(TracingSubscriber.java:68)
	at reactor.core.publisher.MonoNext$NextSubscriber.onNext(MonoNext.java:82)
	at reactor.core.publisher.MonoNext$NextSubscriber.onNext(MonoNext.java:82)
	at io.micronaut.core.async.propagation.ReactivePropagation$2.onNext(ReactivePropagation.java:122)
	at io.reactivex.rxjava3.internal.util.HalfSerializer.onNext(HalfSerializer.java:46)
	at io.reactivex.rxjava3.internal.subscribers.StrictSubscriber.onNext(StrictSubscriber.java:97)
	at io.opentelemetry.javaagent.shaded.instrumentation.rxjava.v3_1_1.TracingSubscriber.onNext(TracingSubscriber.java:43)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableDoFinally$DoFinallySubscriber.onNext(FlowableDoFinally.java:85)
	at io.opentelemetry.javaagent.shaded.instrumentation.rxjava.v3_1_1.TracingSubscriber.onNext(TracingSubscriber.java:43)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableDoOnEach$DoOnEachSubscriber.onNext(FlowableDoOnEach.java:92)
	at io.opentelemetry.javaagent.shaded.instrumentation.rxjava.v3_1_1.TracingSubscriber.onNext(TracingSubscriber.java:43)
	at reactor.core.publisher.StrictSubscriber.onNext(StrictSubscriber.java:89)
	at io.micronaut.http.reactive.execution.FlowAsMono$SubscriptionImpl.forward(FlowAsMono.java:127)
	at io.micronaut.http.reactive.execution.FlowAsMono$SubscriptionImpl.lambda$request$0(FlowAsMono.java:119)
	at io.micronaut.core.execution.ImperativeExecutionFlowImpl.onComplete(ImperativeExecutionFlowImpl.java:132)
	at io.micronaut.core.execution.DelayedExecutionFlowImpl$OnComplete.apply(DelayedExecutionFlowImpl.java:410)
	at io.micronaut.core.execution.DelayedExecutionFlowImpl.work(DelayedExecutionFlowImpl.java:58)
	at io.micronaut.core.execution.DelayedExecutionFlowImpl.completeLazy(DelayedExecutionFlowImpl.java:80)
	at io.micronaut.core.execution.DelayedExecutionFlowImpl.complete(DelayedExecutionFlowImpl.java:99)
	at io.micronaut.core.execution.DelayedExecutionFlow.complete(DelayedExecutionFlow.java:102)
	at io.micronaut.core.execution.ImperativeExecutionFlowImpl.onComplete(ImperativeExecutionFlowImpl.java:132)
	at io.micronaut.core.execution.ExecutionFlow.lambda$async$0(ExecutionFlow.java:92)
	at io.micronaut.core.propagation.PropagatedContext.lambda$wrap$3(PropagatedContext.java:232)
	at io.opentelemetry.javaagent.bootstrap.executors.ContextPropagatingRunnable.run(ContextPropagatingRunnable.java:37)
	at java.base/java.util.concurrent.ThreadPerTaskExecutor$TaskRunner.run(ThreadPerTaskExecutor.java:314)
	at java.base/java.lang.VirtualThread.run(VirtualThread.java:329)
```
We started observing this behaviour when upgrading to Micronaut 4.9.0, which switched the engine from Jetty 11 to 12.
The full log lines on the old behaviour looks like this (with `SENTRY_DEBUG`):
```
{"@timestamp":"2025-08-07T14:30:17.175Z","log.level":"WARN","message":"Failed to encode error response","process.thread.name":"virtual-executor--726278746","log.logger":"io.micronaut.servlet.http.ServletHttpHandler","trace_id":"3869760d8688b9e0d8adeab4b3dbc11f","trace_flags":"00","span_id":"85aa32ce82b11e3c","log":{"origin":{"file":{"name":"ServletHttpHandler.java","line":304},"function":"handleFallback"}},"error.type":"java.lang.IllegalStateException","error.message":"Request/Response does not exist (likely recycled)"}
{"@timestamp":"2025-08-07T14:30:17.176Z","log.level":"ERROR","message":"Failed to execute onComplete","process.thread.name":"virtual-executor--726278746","log.logger":"io.micronaut.core.execution.DelayedExecutionFlowImpl","trace_id":"3869760d8688b9e0d8adeab4b3dbc11f","trace_flags":"00","span_id":"85aa32ce82b11e3c","log":{"origin":{"file":{"name":"DelayedExecutionFlowImpl.java","line":412},"function":"apply"}},"error.type":"java.lang.IllegalStateException","error.message":"Response does not exist (likely recycled)"}
DEBUG: Capturing event: 7a31b0c7131148e19a2eb44e29dc2baa
INFO: Session is null on scope.withSession
{"@timestamp":"2025-08-07T14:30:17.173Z","log.level":"WARN","message":"Failed to encode error response","process.thread.name":"virtual-executor-1277102628","log.logger":"io.micronaut.servlet.http.ServletHttpHandler","trace_id":"4ce20e9f7c4496f7553e26e24b5a21ca","trace_flags":"00","span_id":"d20493963001f8a4","log":{"origin":{"file":{"name":"ServletHttpHandler.java","line":304},"function":"handleFallback"}},"error.type":"java.lang.IllegalStateException","error.message":"Request/Response does not exist (likely recycled)"}
DEBUG: Serializing object: {
  "timestamp": "2025-08-07T14:30:16.514Z",
  "message": {
    "formatted": "Failed to execute onComplete",
    "message": "Failed to execute onComplete"
  },
  "logger": "io.micronaut.core.execution.DelayedExecutionFlowImpl",
  "exception": {
    "values": [
      {
        "type": "IllegalStateException",
        "value": "Response does not exist (likely recycled)",
        "module": "java.lang",
        "thread_id": 1124,
        "stacktrace": {
          "frames": ["..redacted.. frames seen in stack trace above"]
        },
        "mechanism": {
          "type": "LogbackSentryAppender",
          "exception_id": 0
        }
      }
    ]
  },
  "level": "error",
  "fingerprint": [],
  "modules": {
    "redacted"
  },
  "event_id": "b965bbe5730a414eb620f6cbca35b825",
  "contexts": {
    "MDC": {
      "trace_id": "0e63095f7fcb663973c24e5695fd420b",
      "trace_flags": "00",
      "span_id": "b8f0d99b53b3529d"
    },
    "runtime": {
      "name": "Amazon.com Inc",
      "version": "21.0.8"
    },
    "trace": {
      "trace_id": "63132857d43a406582cde58b27f792e1",
      "span_id": "381d016c6c69432d",
      "op": "default",
      "origin": "manual",
      "data": {
        "thread.name": "virtual-executor--860990697",
        "thread.id": "1124"
      }
    }
  },
  "sdk": {
    "name": "sentry.java.logback",
    "version": "8.17.0",
    "packages": [
      {
        "name": "maven:io.sentry:sentry-logback",
        "version": "8.17.0"
      },
      {
        "name": "maven:io.sentry:sentry",
        "version": "8.17.0"
      },
      {
        "name": "maven:io.sentry:sentry-opentelemetry-agent",
        "version": "8.17.0"
      },
      {
        "name": "maven:io.opentelemetry:opentelemetry-sdk",
        "version": "1.51.0"
      },
      {
        "name": "maven:io.opentelemetry.javaagent:opentelemetry-javaagent",
        "version": "2.17.0"
      }
    ],
    "integrations": [
      "OpenTelemetry",
      "OpenTelemetry-Agent",
      "UncaughtExceptionHandler",
      "ShutdownHook",
      "Logback"
    ]
  },
  "platform": "java",
  "user": {},
  "breadcrumbs": ["--redacted-- 800 lines of breadcrumbs"],
  "extra": {
    "thread_name": "virtual-executor--860990697"
  }
}
```
This single error and its breadcrumbs is 86kb, so quite sizeable.

### Actual Result

We don't see the above Response recycled errors, instead the requests just end up hanging ad infinitum, until we either run OOM, block the DB pool or are killed by k8s for missing healthchecks.

This is very odd, we initially thought the Response recycled errors were due to our own mishandling of of `suspend` with Micronaut but maybe not. I've tried to triage this and dive into the changes in 8.18.0, but with no luck. Sadly, I can't invest anymore time in this. My biggest suspicion is this PR: https://github.com/getsentry/sentry-java/pull/4565

Thank you 🙏

**Comment by lcian** [comment]
Thanks for the detailed report @omarhachach!

**Comment by adinauer** [comment]
@omarhachach good news, we were able to reproduce the problem and have a [PR](https://github.com/getsentry/sentry-java/pull/4631) open to fix.

We're planning to release it later today.

We were able to reproduce the behaviour on Micronaut 4.9.0 using `sentry-opentelemetry-agent` version `8.18.0` by setting `SENTRY_AUTO_INIT=false` and initializing Sentry manually later. Due to the delayed `init` Sentry caused `NoOpScopes` to be stored in OpenTelemetry `Context` thus poisoning the `Context` and preventing Sentry from working whenever any of these poisoned `Context` instances was used.

From your log:
```
INFO: Tracing is disabled and this 'startTransaction' returns a no-op.
```
seemed off since you set a `tracesSampleRate` of `0.001`, meaning the message should never be shown.

When testing against the modified version of Sentry from the linked [PR](https://github.com/getsentry/sentry-java/pull/4631), we were able to confirm behaviour is back to not storing `NoOpScopes` onto `Context`.

Thanks for the detailed report!

**Comment by adinauer** [comment]
@omarhachach we've just released https://github.com/getsentry/sentry-java/releases/tag/8.19.1
Could you please test if that fixes the problem?

**Comment by omarhachach** [comment]
> [@omarhachach](https://github.com/omarhachach) we've just released https://github.com/getsentry/sentry-java/releases/tag/8.19.1 Could you please test if that fixes the problem?

Can do tomorrow 🤝

**Comment by omarhachach** [comment]
> [@omarhachach](https://github.com/omarhachach) we've just released https://github.com/getsentry/sentry-java/releases/tag/8.19.1 Could you please test if that fixes the problem?

We're still seeing the same log lines (and result) as 8.18.0, and are not seeing the `Request/Response does not exist (likely recycled)` errors we would've seen on 8.17.1

```
DEBUG: Creating Sentry child span for OpenTelemetry span ddd0346b9d0a87ae (trace 4b68068a98fa1a08ff126879cd62a6d7). Parent span is bd405e03786db147.
DEBUG: Creating Sentry transaction for OpenTelemetry span 21f63b99026b463f (trace 46a9a233428b83fbfeb864ae989d4cb8).
INFO: Tracing is disabled and this 'startTransaction' returns a no-op.
DEBUG: Creating Sentry child span for OpenTelemetry span 858a4b3cfd29653a (trace 46a9a233428b83fbfeb864ae989d4cb8). Parent span is 21f63b99026b463f.
DEBUG: Creating Sentry child span for OpenTelemetry span 37b96687fc56d243 (trace 46a9a233428b83fbfeb864ae989d4cb8). Parent span is 21f63b99026b463f.
DEBUG: Creating Sentry child span for OpenTelemetry span eacda485688e522a (trace 46a9a233428b83fbfeb864ae989d4cb8). Parent span is 21f63b99026b463f.
DEBUG: Creating Sentry child span for OpenTelemetry span c907aeb8def03535 (trace 46a9a233428b83fbfeb864ae989d4cb8). Parent span is eacda485688e522a.
DEBUG: Creating Sentry child span for OpenTelemetry span 73b5528de1350b5c (trace 46a9a233428b83fbfeb864ae989d4cb8). Parent span is 21f63b99026b463f.
DEBUG: SpanExporter exported 24 spans, 0 unset spans remaining.
```

**Comment by adinauer** [comment]
@omarhachach how are you initializing Sentry? Are you relying on the agents auto init or performing init manually?

Can you please also describe what your application is doing?
Is there work being performed on startup, background workers etc?

**Comment by omarhachach** [comment]
> [@omarhachach](https://github.com/omarhachach) how are you initializing Sentry? Are you relying on the agents auto init or performing init manually?
> 
> Can you please also describe what your application is doing? Is there work being performed on startup, background workers etc?

Hi, thanks for getting back. 

Here is some more insight into our setup. We have these dependencies specified:
```gradle
dependencies {
    implementation(platform(libs.sentry.bom)) // io.sentry:sentry-bom
    implementation(libs.sentry.core) // io.sentry:sentry
    implementation(libs.sentry.logback) // io.sentry:sentry-logback
}
```
In our Dockerfile we get the sentry-agent like so (always making sure it is aligned with the BOM above):
```Dockerfile
ADD https://repo1.maven.org/maven2/io/sentry/sentry-opentelemetry-agent/${SENTRY_OTEL_VERSION}/sentry-opentelemetry-agent-${SENTRY_OTEL_VERSION}.jar opentelemetry-javaagent.jar
```
Finally in logback we configure it like so:
```xml
<configuration>
    <appender name="OTEL"
              class="io.opentelemetry.instrumentation.logback.mdc.v1_0.OpenTelemetryAppender"
              captureExperimentalAttributes="true">
    </appender>

    <appender name="SENTRY" class="io.sentry.logback.SentryAppender">
        <options>
            <environment>${STAGE}</environment>
            <release>${BUILD_NUMBER}</release>
            <dsn>REDACTED</dsn>
            <ignoredExceptionsForType>REDACTED</ignoredExceptionsForType>
            <ignoredExceptionsForType>REDACTED</ignoredExceptionsForType>
        </options>
        <!-- Optionally change minimum Event level. Default for Events is ERROR -->
        <minimumEventLevel>ERROR</minimumEventLevel>
        <!-- Optionally change minimum Breadcrumbs level. Default for Breadcrumbs is INFO -->
        <minimumBreadcrumbLevel>TRACE</minimumBreadcrumbLevel>
    </appender>

    <root level="INFO">
        <appender-ref ref="STDOUT_JSON"/>
        <appender-ref ref="OTEL"/>
        <appender-ref ref="SENTRY"/>
    </root>
</configuration>
```
For more insight, we run `io.opentelemetry.instrumentation:opentelemetry-logback-mdc-1.0` with opentelemetry 2.17.0-alpha.
There is no more configuration code-side, from here it is all configured through the agent. We have configure the values like so (relevant config only, also configure exporters, resources etc.):
```yaml
env:
- name: JAVA_TOOL_OPTIONS
  value: "-javaagent:/home/app/opentelemetry-javaagent.jar
- name: OTEL_INSTRUMENTATION_MESSAGING_EXPERIMENTAL_RECEIVE_TELEMETRY_ENABLED
  value: "true"
```

**Comment by omarhachach** [comment]
> [@omarhachach](https://github.com/omarhachach) how are you initializing Sentry? Are you relying on the agents auto init or performing init manually?
> 
> Can you please also describe what your application is doing? Is there work being performed on startup, background workers etc?

Application is a server, we have a little work being performed after initialization such as filling caches which causes outbound calls. Otherwise k8s will be calling health and readiness endpoints, I'm not sure if we exclude those from tracing.

**Comment by adinauer** [comment]
Thanks for the details, we'll try again to reproduce but might take us a bit.

**Comment by lcian** [comment]
Hey @omarhachach, thanks for your cooperation so far.
We've tried our best to reproduce the issue, but we haven't been able to do so.
We're not even sure this is caused by Sentry, as the issue you're experiencing could be due to a bug in your application code, or in one of the many dependencies involved.
To continue, we would need a minimal example that reproduces the problem, or more information that confirms this issue is being caused by Sentry/OpenTelemetry.

**Comment by omarhachach** [comment]
> Hey [@omarhachach](https://github.com/omarhachach), thanks for your cooperation so far. We've tried our best to reproduce the issue, but we haven't been able to do so. We're not even sure this is caused by Sentry, as the issue you're experiencing could be due to a bug in your application code, or in one of the many dependencies involved. To continue, we would need a minimal example that reproduces the problem, or more information that confirms this issue is being caused by Sentry/OpenTelemetry.

Hi, thanks for giving it so much effort. We ended up realising that we weren't instrumenting through the sentry-agent, and have switched to using the pure otel-agent and just relying on sentry-logback (which we were actually instrumenting). That resolved our issue, I still don't know what caused the hanging threads in the version bump, I'll try to get a minimal reproduction up, but for now we can resolve this. I'll re-open when I find the time to do it 🚀

**Comment by adinauer** [comment]
Hey @omarhachach thanks for reporting in. Glad to see you found a workaround.

Could you please clarify some things for us?
1. You used `sentry-opentelemetry-agent` and it worked until upgrading it to `8.18.0`
2. Upgrading `sentry-opentelemetry-agent` to `8.19.1` did not fix the problem for you
3. So you then stopped using `sentry-opentelemetry-agent` and opted to use the [OpenTelemetry Java Agent](https://opentelemetry.io/docs/zero-code/java/agent/) instead
4. What version of our SDK and OpenTelemetry SDK ended up working for you?

**Comment by omarhachach** [comment]
> Hey [@omarhachach](https://github.com/omarhachach) thanks for reporting in. Glad to see you found a workaround.
> 
> Could you please clarify some things for us?
> 
>     1. You used `sentry-opentelemetry-agent` and it worked until upgrading it to `8.18.0`
> 
>     2. Upgrading `sentry-opentelemetry-agent` to `8.19.1` did not fix the problem for you
> 
>     3. So you then stopped using `sentry-opentelemetry-agent` and opted to use the [OpenTelemetry Java Agent](https://opentelemetry.io/docs/zero-code/java/agent/) instead
> 
>     4. What version of our SDK and OpenTelemetry SDK ended up working for you?

For sure,
1. Yes, exactly.
2. Yes, we encountered the same problems as 8.18.0
3. Yes, we were no instrumenting Sentry through `sentry-opentelemetry-agent` but through `sentry-logback`. We were instrumenting OpenTelemetry through the agent though.
4. For the whole time we've been using OpenTelemetry 1.17.0-alpha, and it has worked with Sentry 8.17.1 - 8.21.0. We're just bumping to 8.22.0 now.

**Comment by adinauer** [comment]
Thanks @omarhachach 

> For the whole time we've been using OpenTelemetry 1.17.0-alpha

I assume you mean https://github.com/open-telemetry/opentelemetry-java-instrumentation/releases/tag/v1.17.0 which is roughly three years old. Our SDK in recent versions makes use of https://github.com/open-telemetry/opentelemetry-java-instrumentation/releases/tag/v2.17.0

Was this simply a typo? If not, you could test what happens when using the newer version of the OpenTelemetry Java Agent (non Sentry).

**Comment by omarhachach** [comment]
> Thanks [@omarhachach](https://github.com/omarhachach)
> 
> > For the whole time we've been using OpenTelemetry 1.17.0-alpha
> 
> I assume you mean https://github.com/open-telemetry/opentelemetry-java-instrumentation/releases/tag/v1.17.0 which is roughly three years old. Our SDK in recent versions makes use of https://github.com/open-telemetry/opentelemetry-java-instrumentation/releases/tag/v2.17.0
> 
> Was this simply a typo? If not, you could test what happens when using the newer version of the OpenTelemetry Java Agent (non Sentry).

My bad 😅 I did mean 2.17.0 of the agent and 2.17.0-alpha of the SDK.
