### ISSUE TITLE
Android proguard mapping file - Error: Missing uploaded file

### ISSUE THREAD

**Issue by einschneidend** [getsentry/sentry-java#622]
[INFO] sentry_cli::api request POST https://sentry.io/api/0/projects/OrgName/ProjectName/files/dsyms/
[INFO] sentry_cli::api using token authentication
[INFO] sentry_cli::api sending form data
[INFO] sentry_cli::api > POST /api/0/projects/OrgName/ProjectName/files/dsyms/ HTTP/1.1
[INFO] sentry_cli::api > Host: sentry.io
[INFO] sentry_cli::api > Accept: */*
[INFO] sentry_cli::api > Connection: TE
[INFO] sentry_cli::api > TE: gzip
[INFO] sentry_cli::api > User-Agent: sentry-cli/1.35.5
[INFO] sentry_cli::api > Authorization: Bearer a57d5458***
[INFO] sentry_cli::api > Content-Length: 228
[INFO] sentry_cli::api > Content-Type: multipart/form-data; boundary=------------------------b1d8f431c86402e9
[INFO] sentry_cli::api < HTTP/1.1 400 BAD REQUEST
[INFO] sentry_cli::api < Server: nginx
[INFO] sentry_cli::api < Date: Fri, 05 Oct 2018 23:32:07 GMT
[INFO] sentry_cli::api < Content-Type: application/json
[INFO] sentry_cli::api < Content-Length: 35
[INFO] sentry_cli::api < Connection: keep-alive
[INFO] sentry_cli::api < X-XSS-Protection: 1; mode=block
[INFO] sentry_cli::api < Content-Language: en
[INFO] sentry_cli::api < X-Content-Type-Options: nosniff
[INFO] sentry_cli::api < Vary: Accept-Language, Cookie
[INFO] sentry_cli::api < Allow: GET, POST, HEAD, OPTIONS
[INFO] sentry_cli::api < X-Frame-Options: deny
[INFO] sentry_cli::api < X-Served-By: web-17b74f97
[INFO] sentry_cli::api < Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
[INFO] sentry_cli::api response: 400
[INFO] sentry_cli::api body: {"detail": "Missing uploaded file"}
error: API request failed
  caused by: sentry reported an error: Missing uploaded file (http status: 400)

Properties file:
log.level=debug
defaults.project=ProjectName
defaults.org=OrgName
auth.token=Token

(values seem ok here, not sure what can or cant publish)

proguard file:
-keepattributes LineNumberTable,SourceFile
-dontwarn org.slf4j.**
-dontwarn javax.**
-keep class io.sentry.event.Event { *; }

Help plz.

**Comment by bretthoerner** [comment]
Are you actually trying to upload the file you pasted at the bottom? That is just configuration to run ProGuard on your project (locally). You'd use that with minification enabled (in Gradle) and build an APK, and then a much larger ProGuard mappings file would be generated -- and *that* is what needs to be uploaded to Sentry.

Our Gradle plugin helps manage this process for you: https://docs.sentry.io/clients/java/modules/android/#gradle-integration

**Comment by einschneidend** [comment]
Uhm, nope, I posted my config, including the ProGuard config since it doc says it needs no changes on this file and somewhere else says it needs the line number and so, that's why it's there.

**Comment by bretthoerner** [comment]
OK, what threw me off is the error says `{"detail": "Missing uploaded file"}` and your request says `Content-Length: 228` which is most likely not a valid ProGuard mapping file.

Is this log from the Gradle plugin or are you running it yourself? Are there any other logs at all? Is there a valid ProGuard mappings file in your project build output and if so how large is it?

**Comment by einschneidend** [comment]
Yes, it's from the plugin
Any other logs? Apparently, no.
Yes, mapping is being generated andd I have to check the size

**Comment by einschneidend** [comment]
mapping.txt -> 6322KB

**Comment by bretthoerner** [comment]
Can you share your `build.gradle` and `app/build.gradle` (or equivalents)? Or at least any relevant sections about Sentry, `buildTypes`/`variants` etc?

**Comment by einschneidend** [comment]
Hello again, sorry I was on vacation :p

`app gradle:
apply plugin: 'io.sentry.android.gradle'

    buildTypes {
        release {
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), file('proguard.pro'), file('nologs.pro')
            signingConfig signingConfigs.config
        }

    lintOptions {
        tasks.lint.enabled = true
        disable 'MissingTranslation'
        abortOnError false
    }

sentry {
    // Disables or enables the automatic configuration of proguard
    // for Sentry.  This injects a default config for proguard so
    // you don't need to do it manually.
    autoProguardConfig true

    // Enables or disables the automatic upload of mapping files
    // during a build.  If you disable this you'll need to manually
    // upload the mapping files with sentry-cli when you do a release.
    autoUpload true
}

dependencies {
    implementation fileTree(include: ['*.jar'], dir: 'libs')
     ........
    implementation 'io.sentry:sentry-android:1.7.10'
    implementation 'org.slf4j:slf4j-nop:1.7.25'
}
`

and also the classpath on root gradle file:  classpath 'io.sentry:sentry-android-gradle-plugin:1.7.10'

**Comment by bretthoerner** [comment]
Can you upload or email the entire DEBUG log? I'm curious if the `sentry-cli` ever identifies what file it's actually uploading (the one that's apparently only 228 bytes) to help debug why that file is being selected.

Alternatively I wonder if you could print `args` here in a local build of the Gradle plugin? We should log that or something I suppose.

**Comment by einschneidend** [comment]
email sent

**Comment by einschneidend** [comment]
any feedback? thanks.

**Comment by bretthoerner** [comment]
We need to print the args to `sentry-cli` to figure out what file path it's trying to upload that's so small. I guess it must not do this by default with `DEBUG` enabled.

@mitsuhiko or @jan-auer maybe you have input on whether it'd be easy to change `sentry-cli` to print the args it was invoked with at the `DEBUG` level?

**Comment by mitsuhiko** [comment]
Added in https://github.com/getsentry/sentry-cli/commit/d3bbc8045a9ce9551fffb344e0a98e054a2890ba

**Comment by bretthoerner** [comment]
Awesome, I have no idea what your release schedule is like but I'll include it whenever a release is cut.

**Comment by bretthoerner** [comment]
Hey @einschneidend can you use `1.7.13` with `SENTRY_LOG_LEVEL=debug` and post the logs?

https://github.com/getsentry/sentry-java/releases/tag/v1.7.13

**Comment by einschneidend** [comment]
Hi, I don't see the args, I'm assuming _log.level=debug_ on the properties file is the same
_as SENTRY_LOG_LEVEL=debug_, email sent.

**Comment by bretthoerner** [comment]
Did you upgrade the Gradle plugin version to `1.7.13` also? Or just the Sentry SDK itself?

**Comment by einschneidend** [comment]
oh, my bad, 2nd run.

**Comment by einschneidend** [comment]
Bad news ( actually good news ), it worked this time :\ ( :) )
email sent

**Comment by einschneidend** [comment]
Checked the site and file is there.

**Comment by bretthoerner** [comment]
Very odd. So you're good for now? I guess bump this if you are able to reproduce?

**Comment by einschneidend** [comment]
sure, thanks a lot!

**Comment by einschneidend** [comment]
Fix was to update the lib.

**Comment by 4eRTuk** [comment]
I have this error too with 1.7.13

**Comment by bretthoerner** [comment]
Can you run with `SENTRY_LOG_LEVEL=debug` and post your logs?

**Comment by 4eRTuk** [comment]
Same as @einschneidend 

> Task :app:transformClassesAndResourcesWithProguardForBetaRelease 
  INFO    2018-11-01 22:58:21.912996500 +03:00 Loaded config from C:\Users\...\.sentryclirc
  INFO    2018-11-01 22:58:21.913996400 +03:00 sentry-cli was invoked with the following command line: "C:\\Users\\...\\AppData\\Local\\Temp\\.sentry-cli3711642066634943431.exe" "upload-proguard" "--android-manifest" "C:\\...\\app\\bui
ld\\intermediates\\merged_manifests\\betaRelease\\processBetaReleaseManifest\\merged\\AndroidManifest.xml" "--write-properties" "C:\\...\\app\\build/intermediates/assets/beta/release/sentry-debug-meta.properties" "C:\\...\\app\\build\\outputs\\mapping\\beta\\release\\mapping.txt"
> compressing mappings
> uploading mappings
  DEBUG   2018-11-01 22:58:22.193195500 +03:00 request POST https://sentry.io/api/0/projects/.../files/dsyms/
  DEBUG   2018-11-01 22:58:22.193195500 +03:00 using token authentication
  DEBUG   2018-11-01 22:58:22.193195500 +03:00 sending form data
  DEBUG   2018-11-01 22:58:22.962078 +03:00 > POST /api/0/projects/.../files/dsyms/ HTTP/1.1
  DEBUG   2018-11-01 22:58:22.962078 +03:00 > Host: sentry.io
  DEBUG   2018-11-01 22:58:22.962078 +03:00 > Accept: */*
  DEBUG   2018-11-01 22:58:22.962078 +03:00 > Connection: TE
  DEBUG   2018-11-01 22:58:22.962078 +03:00 > TE: gzip
  DEBUG   2018-11-01 22:58:22.962078 +03:00 > User-Agent: sentry-cli/1.36.3
  DEBUG   2018-11-01 22:58:22.963070600 +03:00 > Authorization: Bearer ...
  DEBUG   2018-11-01 22:58:22.963070600 +03:00 > Content-Length: 228
  DEBUG   2018-11-01 22:58:22.963070600 +03:00 > Content-Type: multipart/form-data; boundary=------------------------04cd73b97b52e858
  DEBUG   2018-11-01 22:58:23.320256800 +03:00 < HTTP/1.1 400 BAD REQUEST
  DEBUG   2018-11-01 22:58:23.320256800 +03:00 < Server: nginx
  DEBUG   2018-11-01 22:58:23.320256800 +03:00 < Date: Thu, 01 Nov 2018 19:58:22 GMT
  DEBUG   2018-11-01 22:58:23.320256800 +03:00 < Content-Type: application/json
  DEBUG   2018-11-01 22:58:23.320256800 +03:00 < Content-Length: 35
  DEBUG   2018-11-01 22:58:23.320256800 +03:00 < Connection: keep-alive
  DEBUG   2018-11-01 22:58:23.320256800 +03:00 < X-XSS-Protection: 1; mode=block
  DEBUG   2018-11-01 22:58:23.320256800 +03:00 < Content-Language: en
  DEBUG   2018-11-01 22:58:23.320256800 +03:00 < X-Content-Type-Options: nosniff
  DEBUG   2018-11-01 22:58:23.320256800 +03:00 < Vary: Accept-Language, Cookie
  DEBUG   2018-11-01 22:58:23.320256800 +03:00 < Allow: GET, POST, DELETE, HEAD, OPTIONS
  DEBUG   2018-11-01 22:58:23.320256800 +03:00 < X-Frame-Options: deny
  DEBUG   2018-11-01 22:58:23.320256800 +03:00 < X-Served-By: web-c9683d4c
  DEBUG   2018-11-01 22:58:23.320256800 +03:00 < Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
  DEBUG   2018-11-01 22:58:23.334255500 +03:00 response: 400
  DEBUG   2018-11-01 22:58:23.334255500 +03:00 body: {"detail": "Missing uploaded file"}
  DEBUG   2018-11-01 22:58:23.336256600 +03:00 skipping update nagger because session is not attended
error: API request failed
  caused by: sentry reported an error: Missing uploaded file (http status: 400)
  DEBUG   2018-11-01 22:58:23.338258 +03:00 client close; no transport to shut down  (from sentry)

**Comment by bretthoerner** [comment]
What's the size of `"C:\...\app\build\outputs\mapping\beta\release\mapping.txt"`? Or did Sentry actually output that path? I'm assuming you elided it.

**Comment by 4eRTuk** [comment]
Yes, I elided the path, but it's correct. Actual file size is 4,03 MB (4 233 256 bytes)

**Comment by bretthoerner** [comment]
OK weird, if that path is a file that exists that is 4MB then this is probably @mitsuhiko or @jan-auer territory.

**Comment by nicusorflorin** [comment]
any word on this? i got the same issue, gradle plugin version is 1.7.15,  the file is generated and is at the correct path, file size: 12MB

**Comment by bretthoerner** [comment]
I think this will require a fix in `sentry-cli`, as it seems like the file has a good size and correct path? @mitsuhiko @jan-auer

**Comment by nicusorflorin** [comment]
well they don't seem to be active :)

**Comment by jan-auer** [comment]
@nicusorflorin I suppose when you pass `--require-one` it fails with `error: found no mapping files to upload` instead?
Also, what are the contents of `sentry-debug-meta.properties` after the command ran?

It would be great if you could send an archive containing your android manifest and the mapping.txt to jan.auer@sentry.io. Thanks!

**Comment by olsh** [comment]
The same issue; also, I've tried to execute the `sentry-cli` command manually, the same error. 
I'm not sure, but probably this is a windows related issue.
Plugin version 1.7.20

@jan-auer I've sent you all these files by email.

**Comment by jan-auer** [comment]
Thank you, I will take a look today.

**Comment by nbransby** [comment]
I have the same problem - works sometimes, others not

**Comment by jan-auer** [comment]
We were able to reproduce the issue on Windows and will land a fix soon.
Ref https://github.com/getsentry/sentry-cli/pull/484

**Comment by jan-auer** [comment]
This should be fixed in `sentry-cli` v1.39.1.

**Comment by ayavilevich** [comment]
Thanks, this seem to have fixed the upload problems I was having with the plugin.

**Comment by olsh** [comment]
Should the Gradle plugin be updated as well?
I still get the error, suppose Gradle plugin uses old version of sentry-cli?

**Comment by ayavilevich** [comment]
@olsh I am running with a local build of the plugin due to another issue. So I supply my own cli exe.
https://github.com/getsentry/sentry-java/issues/667

I think there is a way to configure your release plugin build to use a custom cli exe. See the docs.

**Comment by olsh** [comment]
@ayavilevich thanks for the reply! 👍 
I didn't find a way to configure the plugin with a custom version of CLI.
I suppose that the version should be updated [here](https://github.com/getsentry/sentry-java/blob/master/sentry-android-gradle-plugin/download-sentry-cli.sh#L4)

@jan-auer any chance that the plugin will be updated as well?

Also, it seems like [the docs](https://docs.sentry.io/clients/java/modules/android/) is outdated and suggest to use old version of the plugin.

**Comment by ayavilevich** [comment]
@olsh yes, update in that sh script or download manually and put in the resources/bin folder.

**Comment by ayavilevich** [comment]
@olsh did you try setting the `cli.executable` property in `sentry.properties` file?

https://github.com/getsentry/sentry-java/blob/ef6fbcc2c5d2c97ed1e2b67049a9ca17647dfbf2/sentry-android-gradle-plugin/src/main/groovy/io/sentry/android/gradle/SentryPlugin.groovy#L36

**Comment by bretthoerner** [comment]
Released 1.7.21 with newer sentry-cli

**Comment by stephenrjohnson** [comment]
I'm getting a similar problem debug below:

14:02:15  > Task :app:persistSentryProguardUuidsForReleaseRelease FAILED
14:02:15    INFO    2019-07-10 13:02:13.511351100 +00:00 Loaded config from /root/.sentryclirc
14:02:15    DEBUG   2019-07-10 13:02:13.512602 +00:00 sentry-cli version: 1.40.0, platform: "linux", architecture: "x86_64"
14:02:15    INFO    2019-07-10 13:02:13.513218500 +00:00 sentry-cli was invoked with the following command line: "/tmp/.sentry-cli3045534518321644862.exe" "upload-proguard" "--android-manifest" "/var/jenkins_home/workspace/mobile/(removed)/app/build/intermediates/merged_manifests/release/AndroidManifest.xml" "--write-properties" "/var/jenkins_home/workspace/mobile/(removed)/app/build/intermediates/merged_assets/release/mergeReleaseAssets/out/sentry-debug-meta.properties" "/var/jenkins_home/workspace/mobile/(removed)/app/build/outputs/mapping/release/mapping.txt"
14:02:15    DEBUG   2019-07-10 13:02:13.666236900 +00:00 SHA1 for mapping file '/var/jenkins_home/workspace/mobile/(removed)/app/build/outputs/mapping/release/mapping.txt': '5bbc05c3fc47cac5d312268bc989b361730f5e33'
14:02:15  > compressing mappings
14:02:15  > uploading mappings
14:02:15    DEBUG   2019-07-10 13:02:14.617716800 +00:00 request POST https://sentry.io/api/0/projects/opensignal/(removed)/files/dsyms/
14:02:15    DEBUG   2019-07-10 13:02:14.617765200 +00:00 using token authentication
14:02:15    DEBUG   2019-07-10 13:02:14.617778400 +00:00 sending form data
14:02:15    DEBUG   2019-07-10 13:02:14.617806400 +00:00 retry number 0, max retries: 0
14:02:15    DEBUG   2019-07-10 13:02:15.182969 +00:00 > POST /api/0/projects/(removed)/(removed)/files/dsyms/ HTTP/1.1
14:02:15    DEBUG   2019-07-10 13:02:15.183018500 +00:00 > Host: sentry.io
14:02:15    DEBUG   2019-07-10 13:02:15.183028700 +00:00 > Accept: */*
14:02:15    DEBUG   2019-07-10 13:02:15.183039 +00:00 > Connection: TE
14:02:15    DEBUG   2019-07-10 13:02:15.183049100 +00:00 > TE: gzip
14:02:15    DEBUG   2019-07-10 13:02:15.183059600 +00:00 > User-Agent: sentry-cli/1.40.0
14:02:15    DEBUG   2019-07-10 13:02:15.183659500 +00:00 > Authorization: Bearer c10fc922***
14:02:15    DEBUG   2019-07-10 13:02:15.183698500 +00:00 > Content-Length: 1170478
14:02:15    DEBUG   2019-07-10 13:02:15.183713 +00:00 > Content-Type: multipart/form-data; boundary=------------------------
14:02:15    DEBUG   2019-07-10 13:02:15.334689100 +00:00 response status: 400
14:02:15    DEBUG   2019-07-10 13:02:15.334743 +00:00 body: {"detail":"Missing uploaded file"}
14:02:15    DEBUG   2019-07-10 13:02:15.335114900 +00:00 error: running update nagger
14:02:15    DEBUG   2019-07-10 13:02:15.335151 +00:00 skipping update nagger because session is not attended
14:02:15  error: API request failed
14:02:15    caused by: sentry reported an error: Missing uploaded file (http status: 400)
14:02:15    DEBUG   2019-07-10 13:02:15.335419500 +00:00 client close; no transport to shut down  (from sentry)
14:02:15  
14:02:15  FAILURE: Build failed with an exception.
14:02:15  
14:02:15  * What went wrong:
14:02:15  Execution failed for task ':app:persistSentryProguardUuidsForReleaseRelease'.
14:02:15  > Process 'command '/tmp/.sentry-cli3045534518321644862.exe'' finished with non-zero exit value 1


So I logged into the box:

bash-4.4# ls /var/jenkins_home/workspace/mobile/(removed)/app/build/intermediates/merged_manifests/release/AndroidManifest.xml
/var/jenkins_home/workspace/mobile/(removed)/app/build/intermediates/merged_manifests/release/AndroidManifest.xml
bash-4.4# ls /var/jenkins_home/workspace/mobile/(removed)/app/build/intermediates/merged_manifests/release/AndroidManifest.xml -lh
-rw-r--r-- 1 root root 16K Jul 10 12:53 /var/jenkins_home/workspace/mobile/(removed)/app/build/intermediates/merged_manifests/release/AndroidManifest.xml
bash-4.4# ls -la /var/jenkins_home/workspace/mobile/(removed)/app/build/intermediates/merged_assets/release/mergeReleaseAssets/out/sentry-debug-meta.properties
-rw-r--r-- 1 root root 61 Jul 10 13:02 /var/jenkins_home/workspace/mobile/(removed)/app/build/intermediates/merged_assets/release/mergeReleaseAssets/out/sentry-debug-meta.properties
bash-4.4# ls -lha /var/jenkins_home/workspace/mobile/(removed)/app/build/outputs/mapping/release/mapping.txt
-rw-r--r-- 1 root root 6.3M Jul 10 13:01 /var/jenkins_home/workspace/mobile/(removed)/app/build/outputs/mapping/release/mapping.txt
